name = "tight-truth-243e"
main = "worker.js"
compatibility_date = "2024-04-19"

[[d1_databases]]
# Replace with your actual D1 database name and ID
binding = "DB"
database_name = "stock-db"
database_id = "622ab108-c7b6-4df9-a481-766b7e9a4b30"
